//
//  HomeMovieAppProtocols.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 24/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//

import Foundation
protocol HomeMovieAppViewProtocol: AnyObject {
    var presenter: HomeMovieAppPresenterProtocol? { get }
    
}
protocol HomeMovieAppPresenterProtocol: AnyObject {
    var view: HomeMovieAppViewProtocol? { get }
    var interactor: HomeMovieAppInteractorProtocol? { get }
    var router: HomeMovieAppRouterProtocol?  { get }
    func willFetchMovies()
}

protocol HomeMovieAppInteractorProtocol: AnyObject  {
    var presenter: HomeMovieAppInteractorOutputProtocol? { get }
    func fetchMovies()
}
protocol HomeMovieAppInteractorOutputProtocol: AnyObject {
    
}

protocol HomeMovieAppRouterProtocol: AnyObject {
    func nextViewNavigation()
}

protocol HomeRemoteDataInputProtocol: AnyObject {
    func getMovies()
}

protocol HomeRemoteDataOutputProtocol: AnyObject {
    func didGetMovies()
   
}


